server:
  port: 8082

spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB       # 限制文件上传的大小。默认1     单个文件的限制
      max-request-size: 10MB   # 最大的请求大小，默认10。      一次请求的限制

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

fdfs:
  so-timeout: 2500              # 请求超时时间
  connect-timeout: 600         # 连接超时时间
  thumb-image:                  # 形成缩略图的大小。   上传的图片高清无码，页面展示的时候太大会消耗流量。cdn服务器还是按流量付钱的。而且显示速度也会过慢。所以压缩，体积小，加载速度快
    width: 60
    height: 60
  tracker-list:                 # tracker地址
    - 192.168.25.130:22122

ly:
  upload:
    baseUrl: http://image.leyou.com/
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp